apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-hpa
  namespace: core
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: tech-challenge-deployment
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 75


