apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-deployment
  namespace: tech-challenge
  labels:
    app: tech-challenge
spec:
    replicas: 1
    selector:
      matchLabels:
        app: tech-challenge
    template:
        metadata:
            labels:
                app: tech-challenge
                version: v1
        spec:
            containers:
                -   name: tech-challenge
                    image: fwcpereira/tech-challenge:v2.0.0
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
                    envFrom:
                        - configMapRef:
                            name: tech-challenge-configmap
                        - secretRef:
                            name: tech-challenge-secret
                    livenessProbe:
                        httpGet:
                          path: /heathlz
                          port: 3000
                        initialDelaySeconds: 10
                        failureThreshold: 3
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 1
                    readinessProbe:
                        httpGet:
                            path: /heathlz
                            port: 3000
                        initialDelaySeconds: 5
                        failureThreshold: 3
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 1
                    startupProbe:
                        httpGet:
                            path: /heathlz
                            port: 3000
                        initialDelaySeconds: 10
                        failureThreshold: 3
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 1
                    resources:
                        requests:
                            memory: "350Mi"
                            cpu: "100m"
                        limits:
                            memory: "450Mi"
#                            cpu: "1000m"
            restartPolicy: Always
            terminationGracePeriodSeconds: 30



