apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  namespace: tech-challenge
  labels:
    app: tech-challenge
spec:
    selector:
        app: tech-challenge
    ports:
        -   protocol: TCP
            port: 3000
            targetPort: 3000
    type: ClusterIP
