version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    depends_on:
      - postgres-db
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
