services:

  node-app:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: node-app
    hostname: node-app
    restart: always
    networks:
      - tech-network
    tty: true
    environment:
        DB_HOST: postgres-db
    ports:
      - '3000:3000'
    depends_on:
      postgres-db:
          condition: service_healthy

  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    container_name: postgres-db
    hostname: postgres-db
    restart: always
    networks:
      - tech-network
    tty: true
    ports:
      - '5432:5432'
    volumes:
        - ./postgresql.sql:/docker-entrypoint-initdb.d/init-db.sql
        - ./postgresql_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
    tech-network:
        driver: bridge

volumes:
    postgresql_data:

