# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Defina variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword
ENV POSTGRES_DB mydb

COPY ./postgresql.sql /docker-entrypoint-initdb.d/


# Exponha a porta do PostgreSQL
EXPOSE 5432
