# Use a imagem leve do PostgreSQL
FROM postgres:alpine

# Defina variáveis de ambiente para o PostgreSQL
ENV POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword \
    POSTGRES_DB=mydb \
    POSTGRES_PORT=5432


# Exponha a porta do PostgreSQL (opcional)
EXPOSE 5432
