FROM ubuntu

RUN apt update && \
    apt install -y \
    postgresql-client

COPY ./shared/dump.sql /shared/dump.sql

RUN echo "#!/bin/bash\n\
echo \"Creating role and database...\"\n\
if [ -z \"\$POSTGRES_USER\" ]; then\n\
    echo \"POSTGRES_USER is not set\"\n\
    exit 1\n\
fi\n\
if [ -z \"\$POSTGRES_PASSWORD\" ]; then\n\
    echo \"POSTGRES_PASSWORD is not set\"\n\
    exit 1\n\
fi\n\
if [ -z \"\$POSTGRES_DB\" ]; then\n\
    echo \"POSTGRES_DB is not set\"\n\
    exit 1\n\
fi\n\
if [ -z \"\$POSTGRES_HOST\" ]; then\n\
    echo \"POSTGRES_HOST is not set\"\n\
    exit 1\n\
fi\n\
CREATE_ROLE_COMMAND=\"CREATE ROLE root WITH LOGIN PASSWORD '\$POSTGRES_PASSWORD_ROOT';\"\n\
CREATE_DB_COMMAND=\"CREATE DATABASE root OWNER root;\"\n\
if PGPASSWORD=\$POSTGRES_PASSWORD psql -U \"\$POSTGRES_USER\" -d \"postgres\" -h \"\$POSTGRES_HOST\" -c \"\$CREATE_ROLE_COMMAND\"; then\n\
    echo \"Role 'root' created.\"\n\
else\n\
    echo \"Error creating role 'root'.\"\n\
    exit 1\n\
fi\n\
if PGPASSWORD=\$POSTGRES_PASSWORD psql -U \"\$POSTGRES_USER\" -d \"postgres\" -h \"\$POSTGRES_HOST\" -c \"\$CREATE_DB_COMMAND\"; then\n\
    echo \"Database 'root' created.\"\n\
else\n\
    echo \"Error creating database 'root'.\"\n\
    exit 1\n\
fi\n\
echo \"Restoring dump...\"\n\
if PGPASSWORD=\$POSTGRES_PASSWORD psql -U \"\$POSTGRES_USER\" -d \"\$POSTGRES_DB\" -h \"\$POSTGRES_HOST\" < /shared/dump.sql; then\n\
    echo \"Dump restored\"\n\
else\n\
    echo \"Error restoring dump\"\n\
fi" > /usr/bin/restore_dump.sh

RUN chmod +x /usr/bin/restore_dump.sh
ENTRYPOINT ["/usr/bin/restore_dump.sh"]
CMD ["exit", "0"]
