apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgresql-persistent-volume-claim
    namespace: postgresql
    labels:
        app: postgresql
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi


