apiVersion: apps/v1
kind: Deployment
metadata:
    name: tech-challenge
    namespace: tech-challenge
    labels:
        app: tech-challenge
spec:
    replicas: 3
    selector:
        matchLabels:
            app: tech-challenge
    template:
        metadata:
            name: tech-challenge
            labels:
                app: tech-challenge
        spec:
            containers:
                -   name: tech-challenge
                    image: fwcpereira/tech_challenge:v1.0.0
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
                            protocol: TCP
            restartPolicy: Always

