# Description: Secret for job sidecar-init-job
apiVersion: v1
kind: Secret
metadata:
    name: sidecar-secret
    namespace: sidecar
    labels:
        job: sidecar
type: Opaque
data:
    POSTGRES_USER: cG9zdGdyZXNxbA==
    POSTGRES_PASSWORD: cG9zdGdyZXNxbA==
