# Description: This file contains the definition of a Job that will run a sidecar container to initialize a PostgreSQL database.
apiVersion: batch/v1
kind: Job
metadata:
    name: sidecar-init-job
    namespace: sidecar
spec:
    template:
        spec:
            containers:
                - name: sidecar-init
                  image: fwcpereira/sidecar:v2.0.0
                  env:
                      - name: POSTGRES_DB
                        valueFrom:
                            configMapKeyRef:
                                name: sidecar-configmap
                                key: POSTGRES_DB
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: sidecar-secret
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: sidecar-secret
                                key: POSTGRES_PASSWORD
                  volumeMounts:
                      - mountPath: /docker-entrypoint-initdb.d
                        name: sidecar-dump
                  command:
                      - sh
                      - -c
                      - |
                          echo "Waiting for PostgreSQL to be ready...";
                          while ! pg_isready -h postgresql.postgresql.svc.cluster.local -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do
                            sleep 2;
                          done;
                          echo "PostgreSQL is ready, proceeding with initialization...";
                          PGPASSWORD=$POSTGRES_PASSWORD psql -h postgresql.postgresql.svc.cluster.local -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/dump.sql;
            restartPolicy: OnFailure
            volumes:
                - name: sidecar-dump
                  configMap:
                      name: sidecar-dump
